### ISSUE TITLE
push_to_s3 deployment step from windows machine should use posix separator when uploading folders

### ISSUE THREAD

**Issue by markbruning** [PrefectHQ/prefect-aws#309]
# Expectation / Proposal
`deployments/steps.py:push_to_s3` uses the `\` when uploading files and folders to an s3 bucket. Since prefixes in s3 are determined using `/`, this should be using `.as_posix()` to keep the file/folder structure compliant in s3.

# Traceback / Example
Assuming a structure
```
| - flows
    | - flow.py
prefect.yaml
```
And assuming prefect.yaml push section:
```
push:
  - prefect_aws.deployments.steps.push_to_s3:
      id: push_code
      requires: prefect-aws>=0.3.4
      bucket: <bucket>
      folder: 'PREFECT/'
```
This produces objects in s3
- PREFECT\flows\flow.py
- PREFECT\prefect.yaml

And that's just dirty...

- [X] I would like to [help contribute](https://PrefectHQ.github.io/prefect-aws/#contributing) a pull request to resolve this!
